export const AUTHENTICATION_SUCCESS = 'REGISTER_SUCCESS';
export const AUTHENTICATION_FAILED = 'REGISTER_FAILED';
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';